---
efiSystemPartition:     "/boot/efi"
enableLuksAutomatedPartitioning: true
neverCreateSwap: false
drawNestedPartitions: true
alwaysShowPartitionLabels: true
allowManualPartitioning: true
defaultFileSystemType: "ext4"
initialPartitioningChoice: none
userSwapChoices: [ none, small, suspend, file ]

