---
defaultGroups:
  - cdrom
  - floppy
  - sudo
  - audio
  - dip
  - video
  - plugdev
  - netdev
  - bluetooth
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
reusePassword: false
passwordRequirements:
  minLength: 10
  maxLength: 128
allowWeakPasswords: false

