#!/bin/sh
set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-gui true \
    --firmware-binary true \
    --firmware-chroot true \
    --security true \
    --updates true \
    --memtest none \
    --iso-application "AR OS" \
    --iso-publisher "AR OS contributors" \
    --iso-volume "AR_OS_0_1" \
    --bootappend-live "boot=live components quiet splash username=ar hostname=ar-os locales=en_US.UTF-8 keyboard-layouts=us"

