background = Image("background.png");
background_sprite = Sprite(background.Scale(Window.GetWidth(), Window.GetHeight()));
background_sprite.SetZ(-100);

logo = Image("logo.png");
logo_sprite = Sprite(logo);
logo_sprite.SetX(Window.GetWidth() / 2 - logo.GetWidth() / 2);
logo_sprite.SetY(Window.GetHeight() / 2 - logo.GetHeight() / 2 - 24);

fun refresh_callback () {
    progress = Plymouth.GetBootProgress();
    logo_sprite.SetOpacity(0.72 + 0.28 * Math.Sin(progress * 12));
}

Plymouth.SetRefreshFunction(refresh_callback);

